# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(438, 349)
        self.MainFrame = QtWidgets.QFrame(Dialog)
        self.MainFrame.setGeometry(QtCore.QRect(15, 14, 370, 300))
        self.MainFrame.setMinimumSize(QtCore.QSize(370, 300))
        self.MainFrame.setStyleSheet("background-color:white;\n"
"")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MainFrame.setObjectName("MainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.MainFrame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TopFrame_2 = QtWidgets.QFrame(self.frame_5)
        self.TopFrame_2.setMinimumSize(QtCore.QSize(0, 55))
        self.TopFrame_2.setStyleSheet("background:rgb(51,51,51);")
        self.TopFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TopFrame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TopFrame_2.setObjectName("TopFrame_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.TopFrame_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.minBtnFrame_3 = QtWidgets.QFrame(self.TopFrame_2)
        self.minBtnFrame_3.setMinimumSize(QtCore.QSize(55, 55))
        self.minBtnFrame_3.setMaximumSize(QtCore.QSize(55, 55))
        self.minBtnFrame_3.setStyleSheet("background:transparent;")
        self.minBtnFrame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.minBtnFrame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.minBtnFrame_3.setObjectName("minBtnFrame_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.minBtnFrame_3)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.minBtn_3 = QtWidgets.QPushButton(self.minBtnFrame_3)
        self.minBtn_3.setMinimumSize(QtCore.QSize(30, 30))
        self.minBtn_3.setMaximumSize(QtCore.QSize(30, 30))
        self.minBtn_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/042-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minBtn_3.setIcon(icon)
        self.minBtn_3.setIconSize(QtCore.QSize(30, 30))
        self.minBtn_3.setAutoDefault(False)
        self.minBtn_3.setFlat(True)
        self.minBtn_3.setObjectName("minBtn_3")
        self.horizontalLayout_15.addWidget(self.minBtn_3)
        self.horizontalLayout_14.addWidget(self.minBtnFrame_3)
        self.closeBtnFrame_3 = QtWidgets.QFrame(self.TopFrame_2)
        self.closeBtnFrame_3.setMinimumSize(QtCore.QSize(55, 55))
        self.closeBtnFrame_3.setMaximumSize(QtCore.QSize(55, 55))
        self.closeBtnFrame_3.setStyleSheet("background:transparent;")
        self.closeBtnFrame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.closeBtnFrame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.closeBtnFrame_3.setObjectName("closeBtnFrame_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.closeBtnFrame_3)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.closeBtn_3 = QtWidgets.QPushButton(self.closeBtnFrame_3)
        self.closeBtn_3.setMinimumSize(QtCore.QSize(30, 30))
        self.closeBtn_3.setMaximumSize(QtCore.QSize(30, 30))
        self.closeBtn_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(61, 61, 61)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.closeBtn_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/cancel (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn_3.setIcon(icon1)
        self.closeBtn_3.setIconSize(QtCore.QSize(30, 30))
        self.closeBtn_3.setAutoDefault(False)
        self.closeBtn_3.setFlat(True)
        self.closeBtn_3.setObjectName("closeBtn_3")
        self.horizontalLayout_16.addWidget(self.closeBtn_3)
        self.horizontalLayout_14.addWidget(self.closeBtnFrame_3)
        self.verticalLayout_6.addWidget(self.TopFrame_2)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(self.MainFrame)
        self.frame_2.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(55, 55))
        self.label.setMaximumSize(QtCore.QSize(55, 55))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/close.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.MainFrame)
        self.frame_3.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CancelBtn = QtWidgets.QPushButton(self.frame_4)
        self.CancelBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.CancelBtn.setMaximumSize(QtCore.QSize(120, 30))
        self.CancelBtn.setStyleSheet("\n"
"QPushButton {\n"
"  font: 75 10pt \"Microsoft YaHei UI\";\n"
" color:black;\n"
" background:transparent;\n"
" border-radius:15px;\n"
" border: 3px solid transparent;\n"
" \n"
"    border-color:grey;\n"
" padding:18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" border-color:lightgrey;\n"
"background-color: rgb(240, 240, 240);\n"
"}")
        self.CancelBtn.setObjectName("CancelBtn")
        self.horizontalLayout.addWidget(self.CancelBtn)
        self.DeleteBtn = QtWidgets.QPushButton(self.frame_4)
        self.DeleteBtn.setMaximumSize(QtCore.QSize(120, 30))
        self.DeleteBtn.setStyleSheet("\n"
"QPushButton {\n"
"  font: 75 10pt \"Microsoft YaHei UI\";\n"
" color:black;\n"
" background:transparent;\n"
" border-radius:15px;\n"
" border: 3px solid transparent;\n"
" \n"
"    border-color:rgb(255, 35, 15);\n"
" padding:18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
" border-color:red;\n"
"background-color: rgb(240, 240, 240);\n"
"}")
        self.DeleteBtn.setObjectName("DeleteBtn")
        self.horizontalLayout.addWidget(self.DeleteBtn)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.verticalLayout_7.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "        Are you sure you want to delete this device?"))
        self.CancelBtn.setText(_translate("Dialog", "Cancel"))
        self.DeleteBtn.setText(_translate("Dialog", "Delete"))
        self.checkBox.setText(_translate("Dialog", "Don\'t show this again"))
