# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeviceInformation(object):
    def setupUi(self, DeviceInformation):
        DeviceInformation.setObjectName("DeviceInformation")
        DeviceInformation.setWindowModality(QtCore.Qt.NonModal)
        DeviceInformation.resize(252, 188)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DeviceInformation.sizePolicy().hasHeightForWidth())
        DeviceInformation.setSizePolicy(sizePolicy)
        DeviceInformation.setMaximumSize(QtCore.QSize(252, 16777215))
        DeviceInformation.setLayoutDirection(QtCore.Qt.LeftToRight)
        DeviceInformation.setAutoFillBackground(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(DeviceInformation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DeviceSelection = QtWidgets.QComboBox(DeviceInformation)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.DeviceSelection.setFont(font)
        self.DeviceSelection.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.DeviceSelection.setObjectName("DeviceSelection")
        self.DeviceSelection.addItem("")
        self.DeviceSelection.addItem("")
        self.DeviceSelection.addItem("")
        self.DeviceSelection.addItem("")
        self.DeviceSelection.addItem("")
        self.verticalLayout_2.addWidget(self.DeviceSelection)
        self.TypeOfConnection = QtWidgets.QComboBox(DeviceInformation)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.TypeOfConnection.setFont(font)
        self.TypeOfConnection.setObjectName("TypeOfConnection")
        self.TypeOfConnection.addItem("")
        self.TypeOfConnection.addItem("")
        self.TypeOfConnection.addItem("")
        self.verticalLayout_2.addWidget(self.TypeOfConnection)
        self.BaudRate = QtWidgets.QComboBox(DeviceInformation)
        self.BaudRate.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.BaudRate.setFont(font)
        self.BaudRate.setEditable(True)
        self.BaudRate.setObjectName("BaudRate")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.BaudRate.addItem("")
        self.verticalLayout_2.addWidget(self.BaudRate)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(DeviceInformation)
        self.TypeOfConnection.currentIndexChanged['QString'].connect(self.BaudRate.hide)
        QtCore.QMetaObject.connectSlotsByName(DeviceInformation)


    def retranslateUi(self, DeviceInformation):
        _translate = QtCore.QCoreApplication.translate
        DeviceInformation.setWindowTitle(_translate("DeviceInformation", "Dialog"))
        self.DeviceSelection.setItemText(0, _translate("DeviceInformation", "Select Device"))
        self.DeviceSelection.setItemText(1, _translate("DeviceInformation", "Power Supply"))
        self.DeviceSelection.setItemText(2, _translate("DeviceInformation", "DMM"))
        self.DeviceSelection.setItemText(3, _translate("DeviceInformation", "Chroma Load"))
        self.DeviceSelection.setItemText(4, _translate("DeviceInformation", "Oscilloscope"))
        self.TypeOfConnection.setItemText(0, _translate("DeviceInformation", "Type of connection"))
        self.TypeOfConnection.setItemText(1, _translate("DeviceInformation", "RS232"))
        self.TypeOfConnection.setItemText(2, _translate("DeviceInformation", "LAN"))
        self.BaudRate.setItemText(0, _translate("DeviceInformation", "Baud Rate"))
        self.BaudRate.setItemText(1, _translate("DeviceInformation", "2400"))
        self.BaudRate.setItemText(2, _translate("DeviceInformation", "4800"))
        self.BaudRate.setItemText(3, _translate("DeviceInformation", "9600"))
        self.BaudRate.setItemText(4, _translate("DeviceInformation", "19200"))
        self.BaudRate.setItemText(5, _translate("DeviceInformation", "38400"))
        self.BaudRate.setItemText(6, _translate("DeviceInformation", "57600"))
        self.BaudRate.setItemText(7, _translate("DeviceInformation", "115200"))
        self.BaudRate.setItemText(8, _translate("DeviceInformation", "250000"))
