# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1156, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainFrame.sizePolicy().hasHeightForWidth())
        self.MainFrame.setSizePolicy(sizePolicy)
        self.MainFrame.setStyleSheet("")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopFrame = QtWidgets.QFrame(self.MainFrame)
        self.TopFrame.setMinimumSize(QtCore.QSize(0, 55))
        self.TopFrame.setMaximumSize(QtCore.QSize(16777215, 55))
        self.TopFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TopFrame.setObjectName("TopFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.TopFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ToodleFrame = QtWidgets.QFrame(self.TopFrame)
        self.ToodleFrame.setMinimumSize(QtCore.QSize(80, 55))
        self.ToodleFrame.setMaximumSize(QtCore.QSize(80, 55))
        self.ToodleFrame.setStyleSheet("background-color:#28282B;")
        self.ToodleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ToodleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ToodleFrame.setObjectName("ToodleFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ToodleFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Toodle = QtWidgets.QPushButton(self.ToodleFrame)
        self.Toodle.setMinimumSize(QtCore.QSize(80, 55))
        self.Toodle.setMaximumSize(QtCore.QSize(80, 55))
        self.Toodle.setAutoFillBackground(False)
        self.Toodle.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(61, 61, 61)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.Toodle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/165-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Toodle.setIcon(icon)
        self.Toodle.setIconSize(QtCore.QSize(30, 30))
        self.Toodle.setFlat(True)
        self.Toodle.setObjectName("Toodle")
        self.horizontalLayout_5.addWidget(self.Toodle)
        self.horizontalLayout.addWidget(self.ToodleFrame)
        self.frame_2 = QtWidgets.QFrame(self.TopFrame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_2.setStyleSheet("background:rgb(51,51,51);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.appName = QtWidgets.QFrame(self.frame_2)
        self.appName.setMouseTracking(True)
        self.appName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.appName.setFrameShadow(QtWidgets.QFrame.Plain)
        self.appName.setObjectName("appName")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.appName)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.appName)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.horizontalLayout_6.addWidget(self.appName)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(55, 55))
        self.frame.setMaximumSize(QtCore.QSize(55, 55))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.minBtn = QtWidgets.QPushButton(self.frame)
        self.minBtn.setMaximumSize(QtCore.QSize(55, 55))
        self.minBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(61, 61, 61)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.minBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/042-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minBtn.setIcon(icon1)
        self.minBtn.setIconSize(QtCore.QSize(30, 30))
        self.minBtn.setFlat(True)
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_10.addWidget(self.minBtn)
        self.horizontalLayout_6.addWidget(self.frame)
        self.MaxBtn = QtWidgets.QFrame(self.frame_2)
        self.MaxBtn.setMinimumSize(QtCore.QSize(55, 55))
        self.MaxBtn.setMaximumSize(QtCore.QSize(55, 55))
        self.MaxBtn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MaxBtn.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MaxBtn.setObjectName("MaxBtn")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.MaxBtn)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.maxBtn = QtWidgets.QPushButton(self.MaxBtn)
        self.maxBtn.setMaximumSize(QtCore.QSize(55, 55))
        self.maxBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(61, 61, 61)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.maxBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxBtn.setIcon(icon2)
        self.maxBtn.setIconSize(QtCore.QSize(30, 30))
        self.maxBtn.setFlat(True)
        self.maxBtn.setObjectName("maxBtn")
        self.horizontalLayout_8.addWidget(self.maxBtn)
        self.horizontalLayout_6.addWidget(self.MaxBtn)
        self.CloseBtn = QtWidgets.QFrame(self.frame_2)
        self.CloseBtn.setMinimumSize(QtCore.QSize(55, 55))
        self.CloseBtn.setMaximumSize(QtCore.QSize(55, 55))
        self.CloseBtn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CloseBtn.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CloseBtn.setObjectName("CloseBtn")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.CloseBtn)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.closeBtn = QtWidgets.QPushButton(self.CloseBtn)
        self.closeBtn.setMaximumSize(QtCore.QSize(55, 55))
        self.closeBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(61, 61, 61)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.closeBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/cancel (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon3)
        self.closeBtn.setIconSize(QtCore.QSize(30, 30))
        self.closeBtn.setFlat(True)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_7.addWidget(self.closeBtn)
        self.horizontalLayout_6.addWidget(self.CloseBtn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.TopFrame)
        self.CenterFrame = QtWidgets.QFrame(self.MainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CenterFrame.sizePolicy().hasHeightForWidth())
        self.CenterFrame.setSizePolicy(sizePolicy)
        self.CenterFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.CenterFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CenterFrame.setObjectName("CenterFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CenterFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.westFrame = QtWidgets.QFrame(self.CenterFrame)
        self.westFrame.setMinimumSize(QtCore.QSize(80, 0))
        self.westFrame.setMaximumSize(QtCore.QSize(80, 16777215))
        self.westFrame.setStyleSheet("background:rgb(51,51,51);\n"
"")
        self.westFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.westFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.westFrame.setObjectName("westFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.westFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.westFrame)
        self.frame_5.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_5.setMaximumSize(QtCore.QSize(80, 55))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.homeBtn = QtWidgets.QPushButton(self.frame_5)
        self.homeBtn.setMaximumSize(QtCore.QSize(80, 55))
        self.homeBtn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background:rgb(61, 61, 61)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.homeBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/beach-house.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon4)
        self.homeBtn.setIconSize(QtCore.QSize(30, 30))
        self.homeBtn.setFlat(True)
        self.homeBtn.setObjectName("homeBtn")
        self.horizontalLayout_3.addWidget(self.homeBtn)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.westFrame)
        self.frame_6.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_6.setMaximumSize(QtCore.QSize(80, 55))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 55))
        self.pushButton_2.setText("")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.westFrame)
        self.frame_7.setStyleSheet("background: transparent;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(80, 85))
        self.frame_8.setMaximumSize(QtCore.QSize(80, 85))
        self.frame_8.setStyleSheet("QFrame{\n"
"\n"
"background:transparent;\n"
"\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(14, 0, 0, 25)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMinimumSize(QtCore.QSize(55, 55))
        self.label_4.setMaximumSize(QtCore.QSize(55, 55))
        self.label_4.setStyleSheet("QLabel {\n"
"    border-radius: 30px;\n"
"    background-color: rgb(51,51,51);\n"
"    background:transparent;\n"
"    border: 5px solid rgb(51,51,51);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("resources/asteroid.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.westFrame)
        self.eastFrame = QtWidgets.QFrame(self.CenterFrame)
        self.eastFrame.setStyleSheet("background-color:white")
        self.eastFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.eastFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.eastFrame.setObjectName("eastFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.eastFrame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.eastFrame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setStyleSheet("QTabBar::tab:hover{\n"
"\n"
"    background:transparent;\n"
"    background-color:rgb(238, 238, 238);\n"
"    border:10px\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    border-bottom-color:#C75450\n"
"}\n"
"QTabWidget{\n"
"    border-color:white\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"   border-bottom-color:#C75450;\n"
"border-color:blue;\n"
"min-height:1ex;\n"
"min-width:20ex;\n"
"padding: 5px 5px 10px 10px;\n"
"\n"
"}\n"
"QTabBar::tab:top:selected {\n"
"border-bottom: 1px solid rgb(255, 125, 127);\n"
"\n"
"\n"
"color:#C75450\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    image: url(resources/icon4.png);\n"
"    width: 5px;\n"
"    height: 5px;\n"
"    background:transparent;\n"
"\n"
" }\n"
"QTabBar::close-button:hover {\n"
"    image: url(resources/icon5.png);\n"
"    border-radius: 10px;\n"
"\n"
"\n"
" }\n"
"QTabBar::tab:!selected {\n"
"    bottom:1px;\n"
"    background-colorrgb(241, 241, 241)\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Devices = QtWidgets.QWidget()
        self.Devices.setObjectName("Devices")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Devices)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_11 = QtWidgets.QFrame(self.Devices)
        self.frame_11.setStyleSheet("background-color:white")
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_11)
        self.stackedWidget.setObjectName("stackedWidget")
        self.devicesPage = QtWidgets.QWidget()
        self.devicesPage.setObjectName("devicesPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.devicesPage)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.devicesPage)
        self.scrollArea.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1074, 660))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_12.setStyleSheet("QFrame{\n"
"\n"
"    border-radius:20px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_15.setStyleSheet("")
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setStyleSheet("background:transparent;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setStyleSheet("border-color:black;\n"
"background:transparent;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setLineWidth(5)
        self.frame_17.setMidLineWidth(2)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_4.setMinimumSize(QtCore.QSize(56, 56))
        self.pushButton_4.setMaximumSize(QtCore.QSize(56, 56))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"\n"
"    border-radius: 27px;\n"
"    border-style: outset;\n"
"    background-color:transparent;\n"
"     border: 3px solid transparent;\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(0, 255, 128);\n"
"        \n"
"    }\n"
"\n"
"")
        self.pushButton_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(56, 56))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_10.addWidget(self.pushButton_4)
        self.horizontalLayout_16.addWidget(self.frame_17)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.horizontalLayout_15.addWidget(self.frame_16)
        self.gridLayout_2.addWidget(self.frame_15, 4, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setStyleSheet("background:transparent;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2.addWidget(self.frame_13, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.devicesPage)
        self.scriptPage = QtWidgets.QWidget()
        self.scriptPage.setObjectName("scriptPage")
        self.stackedWidget.addWidget(self.scriptPage)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout_12.addWidget(self.frame_11)
        self.tabWidget.addTab(self.Devices, "")
        self.Terminal = QtWidgets.QWidget()
        self.Terminal.setObjectName("Terminal")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Terminal)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.Terminal)
        self.frame_3.setStyleSheet("background-color: #F2F2F2")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea_2.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background:#F2F2F2;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1056, 642))
        self.scrollAreaWidgetContents_2.setStyleSheet("background: transparent;")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(9)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(9)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setMaximumSize(QtCore.QSize(120, 34))
        self.frame_20.setStyleSheet("\n"
"\n"
"QFrame:hover{\n"
"background-color:rgb(226, 226, 226)\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.comboBox = QtWidgets.QComboBox(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border:transparent;\n"
"    color: black;\n"
"    font: 14px;\n"
"\n"
"}\n"
"QComboBox:focus:out {\n"
"\n"
"    selection-background-color: lightgray;\n"
"    \n"
"}\n"
"\n"
"QComboBox:down-arrow {\n"
"    image: url(resources/arrow.png);\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"QAbstractItemView{\n"
"background:#F2F2F2;\n"
"border:transparent;\n"
"\n"
"}")
        self.comboBox.setIconSize(QtCore.QSize(24, 24))
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/01-Terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/coding1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon7, "")
        self.verticalLayout_16.addWidget(self.comboBox)
        self.horizontalLayout_14.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_4)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_21.setMaximumSize(QtCore.QSize(120, 34))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_14.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_4)
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.scriptStatusLabel = QtWidgets.QLabel(self.frame_22)
        self.scriptStatusLabel.setText("")
        self.scriptStatusLabel.setObjectName("scriptStatusLabel")
        self.verticalLayout_28.addWidget(self.scriptStatusLabel)
        self.horizontalLayout_14.addWidget(self.frame_22)
        self.verticalLayout_15.addWidget(self.frame_4)
        self.frame_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_23)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.terminalEdit = QtWidgets.QTextEdit(self.page)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.terminalEdit.setFont(font)
        self.terminalEdit.setMouseTracking(True)
        self.terminalEdit.setStyleSheet("\n"
"QTextEdit{\n"
"border:1px solid #AFACAC;\n"
"background-color: #FFFFFF\n"
"}")
        self.terminalEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.terminalEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.terminalEdit.setOverwriteMode(True)
        self.terminalEdit.setTabStopWidth(80)
        self.terminalEdit.setCursorWidth(3)
        self.terminalEdit.setPlaceholderText("")
        self.terminalEdit.setObjectName("terminalEdit")
        self.verticalLayout_19.addWidget(self.terminalEdit)
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_24 = QtWidgets.QFrame(self.page_2)
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.textEdit = QtWidgets.QTextEdit(self.frame_24)
        self.textEdit.setStyleSheet("\n"
"QTextEdit{\n"
"border:1px solid #AFACAC;\n"
"background-color: #FFFFFF\n"
"}")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_20.addWidget(self.textEdit)
        self.gridLayout_5.addWidget(self.frame_24, 0, 0, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.page_2)
        self.frame_25.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setMinimumSize(QtCore.QSize(0, 32))
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_14 = QtWidgets.QFrame(self.frame_26)
        self.frame_14.setMaximumSize(QtCore.QSize(34, 34))
        self.frame_14.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background-color:rgb(226, 226, 226)\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border:transparent;\n"
"}")
        self.pushButton_5.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon8)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_14.addWidget(self.pushButton_5)
        self.verticalLayout_22.addWidget(self.frame_14)
        self.frame_18 = QtWidgets.QFrame(self.frame_26)
        self.frame_18.setMaximumSize(QtCore.QSize(34, 34))
        self.frame_18.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background-color:rgb(226, 226, 226)\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border:transparent;\n"
"}")
        self.pushButton_3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon9)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_13.addWidget(self.pushButton_3)
        self.verticalLayout_22.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_26)
        self.frame_19.setMaximumSize(QtCore.QSize(34, 34))
        self.frame_19.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background-color:rgb(226, 226, 226)\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton = QtWidgets.QPushButton(self.frame_19)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:transparent;\n"
"}")
        self.pushButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resources/stop-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon10)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_11.addWidget(self.pushButton)
        self.verticalLayout_22.addWidget(self.frame_19)
        self.verticalLayout_21.addWidget(self.frame_26)
        self.gridLayout_5.addWidget(self.frame_25, 0, 2, 1, 1)
        self.frame_27 = QtWidgets.QFrame(self.page_2)
        self.frame_27.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setMinimumSize(QtCore.QSize(0, 34))
        self.frame_28.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frame_28.setStyleSheet("")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_30 = QtWidgets.QFrame(self.frame_28)
        self.frame_30.setMinimumSize(QtCore.QSize(24, 24))
        self.frame_30.setMaximumSize(QtCore.QSize(24, 16777215))
        self.frame_30.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background-color:rgb(225, 225, 225)\n"
"}")
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_6.setMaximumSize(QtCore.QSize(24, 16777215))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border:transparent;\n"
"}")
        self.pushButton_6.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resources/plus (5).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon11)
        self.pushButton_6.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_25.addWidget(self.pushButton_6)
        self.horizontalLayout_17.addWidget(self.frame_30)
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setMinimumSize(QtCore.QSize(24, 24))
        self.frame_29.setMaximumSize(QtCore.QSize(24, 16777215))
        self.frame_29.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background-color:rgb(226, 226, 226)\n"
"}")
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_7.setMaximumSize(QtCore.QSize(24, 16777215))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border:transparent;\n"
"}")
        self.pushButton_7.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("resources/delete (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon12)
        self.pushButton_7.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_24.addWidget(self.pushButton_7)
        self.horizontalLayout_17.addWidget(self.frame_29)
        self.verticalLayout_23.addWidget(self.frame_28)
        self.listWidget = QtWidgets.QListWidget(self.frame_27)
        self.listWidget.setStyleSheet("\n"
"QListWidget{\n"
"border:1px solid #AFACAC;\n"
"background-color: #FFFFFF;\n"
"}")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_23.addWidget(self.listWidget)
        self.frame_31 = QtWidgets.QFrame(self.frame_27)
        self.frame_31.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background-color:rgb(226, 226, 226)\n"
"}")
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.timeSensitiveCheckBox = QtWidgets.QCheckBox(self.frame_31)
        self.timeSensitiveCheckBox.setAutoFillBackground(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("resources/dinosaur.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.timeSensitiveCheckBox.setIcon(icon13)
        self.timeSensitiveCheckBox.setTristate(False)
        self.timeSensitiveCheckBox.setObjectName("timeSensitiveCheckBox")
        self.verticalLayout_26.addWidget(self.timeSensitiveCheckBox)
        self.verticalLayout_23.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_27)
        self.frame_32.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background-color:rgb(226, 226, 226)\n"
"}")
        self.frame_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.PythonCB = QtWidgets.QCheckBox(self.frame_32)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("resources/python.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PythonCB.setIcon(icon14)
        self.PythonCB.setObjectName("PythonCB")
        self.verticalLayout_27.addWidget(self.PythonCB)
        self.verticalLayout_23.addWidget(self.frame_32)
        self.gridLayout_5.addWidget(self.frame_27, 0, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_2)
        self.verticalLayout_18.addWidget(self.stackedWidget_2)
        self.verticalLayout_15.addWidget(self.frame_23)
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.textEdit_2.setStyleSheet("\n"
"QTextEdit{\n"
"border:1px solid #AFACAC;\n"
"background-color: #FFFFFF\n"
"}")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_15.addWidget(self.textEdit_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("resources/terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Terminal, icon15, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.bottomFrame = QtWidgets.QFrame(self.eastFrame)
        self.bottomFrame.setMinimumSize(QtCore.QSize(0, 20))
        self.bottomFrame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bottomFrame.setStyleSheet("background:rgb(51,51,51);")
        self.bottomFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bottomFrame.setObjectName("bottomFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.bottomFrame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_10 = QtWidgets.QFrame(self.bottomFrame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.statusLabel = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("QLabel{\n"
"color:white;\n"
"}")
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_11.addWidget(self.statusLabel)
        self.horizontalLayout_12.addWidget(self.frame_10)
        self.drag = QtWidgets.QFrame(self.bottomFrame)
        self.drag.setMinimumSize(QtCore.QSize(20, 20))
        self.drag.setMaximumSize(QtCore.QSize(20, 20))
        self.drag.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drag.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drag.setObjectName("drag")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.drag)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtWidgets.QLabel(self.drag)
        self.label.setMinimumSize(QtCore.QSize(20, 20))
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.horizontalLayout_12.addWidget(self.drag)
        self.verticalLayout_6.addWidget(self.bottomFrame)
        self.horizontalLayout_2.addWidget(self.eastFrame)
        self.verticalLayout.addWidget(self.CenterFrame)
        self.gridLayout.addWidget(self.MainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Chixculub Impactor"))
        self.minBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Minimize</p></body></html>"))
        self.maxBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Close</p></body></html>"))
        self.homeBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Home</p></body></html>"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>New Device</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Devices), _translate("MainWindow", "Devices"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Terminal"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Script"))
        self.terminalEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; color:#0033b3;\">Enter Command &gt;&gt; </span></p></body></html>"))
        self.timeSensitiveCheckBox.setText(_translate("MainWindow", "Time sensitive"))
        self.PythonCB.setText(_translate("MainWindow", "Python"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">adsdas</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Terminal), _translate("MainWindow", "Terminal 1"))
